from . import paths_helper  # noqa: F401  — registers ComfyUI/models/llm
from .bonus_image_intent import (
    NODE_CLASS_MAPPINGS as _BONUS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _BONUS_DISPLAY_NAME_MAPPINGS,
)
from .nodes import NODE_CLASS_MAPPINGS as _CORE_NODE_CLASS_MAPPINGS
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as _CORE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**_CORE_NODE_CLASS_MAPPINGS, **_BONUS_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {
    **_CORE_DISPLAY_NAME_MAPPINGS,
    **_BONUS_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
